import { relations, sql } from "drizzle-orm";
import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

// Columns are written camelCase and stored snake_case (casing: "snake_case" in db + drizzle.config).

// ---------------------------------------------------------------------------------------------
// Better Auth. Generated by `npx auth@1.7.6 generate` (the Better Auth CLI) and kept verbatim:
// the adapter maps to these exact tables and columns, so regenerate rather than hand-edit.
// ---------------------------------------------------------------------------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  role: text("role").default("customer").notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// ---------------------------------------------------------------------------------------------
// Catalogue
// ---------------------------------------------------------------------------------------------

export const department = pgEnum("department", ["women", "men", "unisex"]);

export const categories = pgTable("categories", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull().unique(),
  name: text().notNull(),
  description: text().notNull(),
  // Categories with an image are the homepage Collections strip.
  imageUrl: text(),
  imageAlt: text(),
  position: integer().notNull().default(0),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
});

export const categoriesRelations = relations(categories, ({ many }) => ({
  products: many(products),
}));

export const products = pgTable(
  "products",
  {
    id: uuid().primaryKey().defaultRandom(),
    slug: text().notNull().unique(),
    name: text().notNull(),
    description: text().notNull(),
    categoryId: uuid()
      .notNull()
      .references(() => categories.id, { onDelete: "restrict" }),
    department: department().notNull(),
    colour: text().notNull(),
    // Money is integer cents; only mapProduct() in src/lib/products.ts converts to dollars.
    priceCents: integer().notNull(),
    compareAtCents: integer(),
    // Stock is a quantity plus a flag; the UI state is derived by stockState() in src/lib/stock.ts.
    stockQuantity: integer().notNull().default(0),
    madeToOrder: boolean().notNull().default(false),
    stockDetail: text(),
    isGift: boolean().notNull().default(false),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp({ withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    check("products_price_positive", sql`${t.priceCents} > 0`),
    check("products_compare_at_above_price", sql`${t.compareAtCents} is null or ${t.compareAtCents} > ${t.priceCents}`),
    check("products_stock_non_negative", sql`${t.stockQuantity} >= 0`),
    index("products_category_idx").on(t.categoryId),
    index("products_created_at_idx").on(t.createdAt.desc()),
  ],
);

export const productsRelations = relations(products, ({ one, many }) => ({
  category: one(categories, { fields: [products.categoryId], references: [categories.id] }),
  images: many(productImages),
}));

export const productImages = pgTable(
  "product_images",
  {
    id: uuid().primaryKey().defaultRandom(),
    productId: uuid()
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    url: text().notNull(),
    // Alt belongs to the row, not the asset: the same URL is reused with different copy.
    alt: text().notNull(),
    // 0 is the packshot.
    position: integer().notNull().default(0),
  },
  (t) => [unique("product_images_product_position_unique").on(t.productId, t.position)],
);

export const productImagesRelations = relations(productImages, ({ one }) => ({
  product: one(products, { fields: [productImages.productId], references: [products.id] }),
}));

// ─── Bag ─────────────────────────────────────────────────────────────────────
// One row per (user, product, size). No price column: amounts are always read live from products.
// Deleting a product (e.g. db:seed) or a user removes their bag lines.
export const cartItems = pgTable(
  "cart_items",
  {
    userId: text().notNull().references(() => user.id, { onDelete: "cascade" }),
    productId: uuid().notNull().references(() => products.id, { onDelete: "cascade" }),
    size: text().notNull().default(""), // display-only size; "" for one-size categories
    quantity: integer().notNull(),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.productId, t.size] }),
    check("cart_items_quantity_range", sql`${t.quantity} between 1 and 10`),
  ],
);

export const cartItemsRelations = relations(cartItems, ({ one }) => ({
  user: one(user, { fields: [cartItems.userId], references: [user.id] }),
  product: one(products, { fields: [cartItems.productId], references: [products.id] }),
}));

// ─── Orders ──────────────────────────────────────────────────────────────────
// Created "pending" when checkout starts (prices and items snapshotted from our DB), then moved
// forward only by Stripe-verified events via applyCheckoutSession in src/lib/orders.ts.
export const orderStatus = pgEnum("order_status", ["pending", "processing", "paid", "payment_failed", "expired"]);

export const orders = pgTable(
  "orders",
  {
    id: uuid().primaryKey().defaultRandom(),
    // Financial record: never cascaded away with the user.
    userId: text().notNull().references(() => user.id, { onDelete: "restrict" }),
    status: orderStatus().notNull().default("pending"),
    subtotalCents: integer().notNull(), // from our products table at checkout start
    amountTotalCents: integer(), // what Stripe reports it charged, set on payment
    currency: text().notNull().default("usd"),
    stripeCheckoutSessionId: text().unique(),
    stripePaymentIntentId: text(),
    customerEmail: text(),
    shippingName: text(),
    shippingAddress: jsonb(), // Stripe's collected address, as returned
    stockShortfall: boolean().notNull().default(false), // stock was below the order when it was paid (oversell)
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    paidAt: timestamp({ withTimezone: true }),
  },
  (t) => [
    index("orders_user_created_idx").on(t.userId, t.createdAt.desc()),
    check("orders_subtotal_positive", sql`${t.subtotalCents} > 0`),
  ],
);

export const orderItems = pgTable(
  "order_items",
  {
    id: uuid().primaryKey().defaultRandom(),
    orderId: uuid().notNull().references(() => orders.id, { onDelete: "cascade" }),
    // Snapshot below keeps the order readable if the product is later deleted.
    productId: uuid().references(() => products.id, { onDelete: "set null" }),
    slug: text().notNull(),
    name: text().notNull(),
    size: text().notNull().default(""),
    unitPriceCents: integer().notNull(),
    quantity: integer().notNull(),
  },
  (t) => [
    index("order_items_order_idx").on(t.orderId),
    check("order_items_quantity_positive", sql`${t.quantity} > 0`),
    check("order_items_price_positive", sql`${t.unitPriceCents} > 0`),
  ],
);

export const ordersRelations = relations(orders, ({ one, many }) => ({
  user: one(user, { fields: [orders.userId], references: [user.id] }),
  items: many(orderItems),
}));

export const orderItemsRelations = relations(orderItems, ({ one }) => ({
  order: one(orders, { fields: [orderItems.orderId], references: [orders.id] }),
  product: one(products, { fields: [orderItems.productId], references: [products.id] }),
}));
